<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Company;
use App\Models\Branch;

class CompanyBranchSeeder extends Seeder
{
    public function run()
    {
        // 1 Company (updated with real information)
        $company = Company::create([
            'company_name_th' => 'บริษัทเเม๊กซ์ เพาเวอร์ จำกัด',
            'company_name_en' => 'Max Power Co., Ltd.',
            'tax_no'          => '0115542003515',
            'company_logo'    => 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGMAAQAABQABDQottAAAAABJRU5ErkJggg==',
        ]);

        $this->command->info('Starting CompanyBranchSeeder with new B pattern...');
        $createdBranches = [];

        // Create only Head Office with provided contact details
        $branch = Branch::create([
            'company_id'         => $company->id,
            // branch_code will be auto-generated by the model hook
            'name_th'            => 'สำนักงานใหญ่',
            'name_en'            => 'Head Office',
            'address_th'         => 'เลขที่ 279 ซอยพหลโยธิน 48 แยก 53 แขวงท่าแร้ง เขตบางเขน กทม 10220',
            'address_en'         => 'No. 279 Soi Phahonyothin 48, Yaek 53, Tharang, Bang Khen, Bangkok 10220',
            'bill_address_th'    => 'เลขที่ 279 ซอยพหลโยธิน 48 แยก 53 แขวงท่าแร้ง เขตบางเขน กทม 10220',
            'bill_address_en'    => 'No. 279 Soi Phahonyothin 48, Yaek 53, Tharang, Bang Khen, Bangkok 10220',
            'post_code'          => '10220',
            'phone_country_code' => '+66',
            'phone_number'       => '029731134',
            'fax'                => '029731430',
            'website'            => null,
            'email'              => null,
            'is_head_office'     => true,
            'branch_status_id'   => 1, // Active status
            'latitude'           => null,
            'longitude'          => null,
            'contact_name'       => null,
            'contact_email'      => null,
            'contact_mobile'     => null,
        ]);

        // Store branch info for logging
        $createdBranches[] = [
            'id' => $branch->id,
            'branch_code' => $branch->branch_code,
            'name_en' => $branch->name_en,
            'is_head_office' => $branch->is_head_office ? 'Yes' : 'No'
        ];

        $this->command->info('CompanyBranchSeeder completed successfully.');
        
        // Display generated branch codes
        $this->command->info('Generated Branch Codes:');
        foreach ($createdBranches as $branch) {
            $this->command->line("  - Code: {$branch['branch_code']} | {$branch['name_en']} [Head Office: {$branch['is_head_office']}]");
        }
    }
}
