@echo off
echo Checking Laravel logs for transfer form debugging...
echo.
echo Looking for lines containing "WarehouseAddTransferForm" or "Form submit event triggered"...
echo.
type storage\logs\laravel.log | findstr /i "WarehouseAddTransferForm"
echo.
echo Looking for form submit events...
type storage\logs\laravel.log | findstr /i "Form submit event triggered"
echo.
echo Looking for any errors...
type storage\logs\laravel.log | findstr /i "error"
echo.
echo Done! Press any key to exit...
pause > nul
